### ISSUE TITLE
Should the UI refresh when Angular HTML files are updated?

### ISSUE THREAD

**Issue by wwarby** [rajeshsuramalla/AngularWithDotNetCoreElectronNET#12]
Thanks for building this starter project - I'm looking to use it as a launching point for a new project and it looks like it's going to get me up and running very quickly. Only issue I can see is that it says on the home page that "your client-side resources are dynamically built on demand and the page refreshes when you modify any file" - however I tested changing the "Hello, world!" heading in `home.component.html` and saved, expecting the UI to update itself, and it didn't. Restarting my app for every UI change is going to be somewhat of a nuisance to my development process so I'd really like to get automatic recompile working before I get started - any ideas?

**Comment by rajeshsuramalla** [comment]
Hello,
You can use **electronize start /watch**

The file watcher is included with version 8.31.1 of Electron.NET. For example, a file change can trigger compilation, test execution, or deployment. The Electron.NET window will automatically refresh and new code changes will be visible more quickly.

For more information, please refer following URL https://github.com/ElectronNET/Electron.NET.

I hope it will be helpful for you.
Thank you.
